# A container for street_parking application

ARG VERSION=16.04
FROM ubuntu:${VERSION}

MAINTAINER Krishnasagar <pagesagar@gmail.com>

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update && apt-get install -y build-essential python3.6 python3.6-dev python3-pip

COPY . /root/street_parking
WORKDIR /root/street_parking

RUN chmod +x setup.sh
CMD /bin/bash -c "./setup.sh"